/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-x86_64"
#define DATE "built on: Sun Mar 10 08:46:01 2024 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','/','h','o','m','e','/',
    'z','e','h','n','/','l','u','c','k','f','o','x','-','p','i','c',
    'o','/','t','o','o','l','s','/','l','i','n','u','x','/','t','o',
    'o','l','c','h','a','i','n','/','a','r','m','-','r','o','c','k',
    'c','h','i','p','8','3','0','-','l','i','n','u','x','-','u','c',
    'l','i','b','c','g','n','u','e','a','b','i','h','f','/','b','i',
    'n','/','a','r','m','-','r','o','c','k','c','h','i','p','8','3',
    '0','-','l','i','n','u','x','-','u','c','l','i','b','c','g','n',
    'u','e','a','b','i','h','f','-','g','c','c',' ','-','f','P','I',
    'C',' ','-','p','t','h','r','e','a','d',' ',' ','-','W','a','l',
    'l',' ','-','O','3',' ','-','D','O','P','E','N','S','S','L','_',
    'U','S','E','_','N','O','D','E','L','E','T','E',' ','-','D','L',
    '_','E','N','D','I','A','N',' ','-','D','O','P','E','N','S','S',
    'L','_','P','I','C',' ','-','D','N','D','E','B','U','G','\0'
};
